# app/core/multimodal_agent.py
# LangGraph multimodal agent with specialized routing nodes.
#
# Design principle: each node is independently testable and optimizable.
# If vision answers are poor, improve VisionNode without touching TextNode.
# If calculations are wrong, fix ToolNode without touching retrieval.

from typing import TypedDict, Annotated, Literal
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages
from dotenv import load_dotenv
load_dotenv()

from app.core.tools import calculator, get_current_date, compute_growth_rate, web_search
from app.config import settings

# ── Agent State ───────────────────────────────────────────────────────────────
# Everything the agent needs to track across nodes.
# Each node reads from and writes to this state.

class MultimodalAgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]

    # Routing decision made by supervisor
    route: str

    # Retrieved documents from vector store
    retrieved_docs: list[Document]

    # Formatted context string built from retrieved docs
    context: str

    # Final answer produced by synthesizer
    answer: str

# ── Content type filters ──────────────────────────────────────────────────────
# These filter the vector store retrieval by content_type metadata.
# This is metadata filtering — only return chunks of the specified type.

TEXT_FILTER = {"content_type": {"$in": ["text"]}}
VISION_FILTER = {"content_type": {"$in": ["image", "chart", "mixed", "scanned"]}}
ALL_FILTER = None  # no filter — retrieve all content types

# ── Prompts ───────────────────────────────────────────────────────────────────

SUPERVISOR_PROMPT = """You are a routing assistant for a multimodal document intelligence system.

Classify the user's question into exactly one of these routes:

- "text"    → question about written content, facts, numbers in text
- "vision"  → question about charts, graphs, images, diagrams, visual content
- "tools"   → question requiring calculation, date arithmetic, or growth rates
- "compare" → question comparing text data with visual data, or asking for both
- "web"     → question about current events or information not in the documents

Respond with ONLY the route name, nothing else.
Examples:
  "What was GDP in 2013?" → text
  "What does the bar chart show?" → vision
  "Calculate the CAGR" → tools
  "How does the chart compare to the text data?" → compare
  "What is the current exchange rate?" → web"""

VISION_SYSTEM_PROMPT = """You are a visual content analyst.
Answer questions about charts, graphs, images, and visual documents.
The context below contains descriptions of visual content generated by AI vision analysis.
Be specific about data points, trends, and visual patterns you find in the descriptions.
Always cite [Source type, Page X] for each piece of information."""

TEXT_SYSTEM_PROMPT = """You are a document analyst.
Answer questions about text content from documents.
Be precise with numbers, dates, and facts.
Always cite [Source type, Page X] for each piece of information."""

COMPARE_SYSTEM_PROMPT = """You are a multimodal document analyst.
You have access to both text content and visual content descriptions.
Compare and synthesize information across both content types.
Note any consistencies or discrepancies between text and visual data.
Always cite [Source type, Page X] for each piece of information."""

SYNTHESIZER_PROMPT = """You are a helpful research assistant.
Provide a clear, complete answer based on the analysis below.
Include specific data points and cite sources."""

def format_docs_with_types(docs: list[Document]) -> str:
    """Formats docs with content type labels for context."""
    if not docs:
        return "No relevant content found."

    type_labels = {
        "text": "📄 Text",
        "image": "🖼️ Image",
        "chart": "📊 Chart",
        "scanned": "📷 Scanned",
        "mixed": "📑 Mixed",
    }

    formatted = []
    for i, doc in enumerate(docs):
        page = doc.metadata.get("page", "?")
        ct = doc.metadata.get("content_type", "text")
        fname = doc.metadata.get("file_name", "unknown")
        label = type_labels.get(ct, "📄")

        formatted.append(
            f"[Source {i+1} | {label} | {fname} | Page {page}]\n"
            f"{doc.page_content}"
        )

    return "\n\n---\n\n".join(formatted)

def build_multimodal_agent(vectorstore):
    """
    Builds a LangGraph multimodal agent with specialized routing nodes.

    Args:
        vectorstore: ChromaDB vector store with multimodal chunks

    Returns:
        Compiled LangGraph application
    """
    llm = ChatOpenAI(
        model=settings.openai_chat_model,
        temperature=0,
        api_key=settings.openai_api_key
    )

    tools = [calculator, get_current_date, compute_growth_rate, web_search]
    llm_with_tools = llm.bind_tools(tools)

    # ── Node 1: Supervisor ───────────────────────────────────────────────────
    # Classifies the question and sets the route.

    def supervisor_node(state: MultimodalAgentState) -> dict:
        """
        Reads the latest human message and decides which node
        should handle it. Returns the routing decision.
        """
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        response = llm.invoke([
            SystemMessage(content=SUPERVISOR_PROMPT),
            HumanMessage(content=last_human)
        ])

        route = response.content.strip().lower()

        # Validate route — fall back to "text" if unexpected value
        valid_routes = {"text", "vision", "tools", "compare", "web"}
        if route not in valid_routes:
            route = "text"

        print(f"  [Supervisor] Routing to: {route}")
        return {"route": route}

    # ── Node 2: Text node ────────────────────────────────────────────────────
    # Retrieves text chunks only and generates answer.

    def text_node(state: MultimodalAgentState) -> dict:
        """Handles questions about text content."""
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        # Retrieve text chunks only using metadata filter
        retriever = vectorstore.as_retriever(
            search_kwargs={
                "k": 6,
                "filter": TEXT_FILTER
            }
        )
        docs = retriever.invoke(last_human)
        context = format_docs_with_types(docs)

        response = llm.invoke([
            SystemMessage(content=TEXT_SYSTEM_PROMPT),
            *state["messages"][:-1],  # history
            HumanMessage(content=f"Context:\n{context}\n\nQuestion: {last_human}")
        ])

        return {
            "retrieved_docs": docs,
            "context": context,
            "answer": response.content,
            "messages": [AIMessage(content=response.content)]
        }

    # ── Node 3: Vision node ──────────────────────────────────────────────────
    # Retrieves visual content chunks only.

    def vision_node(state: MultimodalAgentState) -> dict:
        """Handles questions about charts, images, and visual content."""
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        # Retrieve visual chunks only
        retriever = vectorstore.as_retriever(
            search_kwargs={
                "k": 6,
                "filter": VISION_FILTER
            }
        )
        docs = retriever.invoke(last_human)
        context = format_docs_with_types(docs)

        response = llm.invoke([
            SystemMessage(content=VISION_SYSTEM_PROMPT),
            *state["messages"][:-1],
            HumanMessage(content=f"Visual content context:\n{context}\n\nQuestion: {last_human}")
        ])

        return {
            "retrieved_docs": docs,
            "context": context,
            "answer": response.content,
            "messages": [AIMessage(content=response.content)]
        }

    # ── Node 4: Tools node ───────────────────────────────────────────────────
    # Handles calculation and tool-calling questions.

    def tools_node(state: MultimodalAgentState) -> dict:
        """Handles questions requiring calculations or tool use."""
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        # Get context from all chunk types to find numbers
        retriever = vectorstore.as_retriever(search_kwargs={"k": 4})
        docs = retriever.invoke(last_human)
        context = format_docs_with_types(docs)

        tool_system = f"""You are a precise calculation assistant.
Use the available tools to answer the question.
Relevant document context for reference:
{context}

Available tools: calculator, compute_growth_rate, get_current_date
Always show your calculation steps."""

        messages = [
            SystemMessage(content=tool_system),
            *state["messages"]
        ]

        # Agent loop — keep calling tools until done
        max_iterations = 5
        for _ in range(max_iterations):
            response = llm_with_tools.invoke(messages)
            messages.append(response)

            if not response.tool_calls:
                break

            # Execute each tool call
            from langchain_core.messages import ToolMessage
            for tool_call in response.tool_calls:
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]

                tool_map = {
                    "calculator": calculator,
                    "get_current_date": get_current_date,
                    "compute_growth_rate": compute_growth_rate,
                    "web_search": web_search,
                }

                if tool_name in tool_map:
                    result = tool_map[tool_name].invoke(tool_args)
                    messages.append(ToolMessage(
                        content=str(result),
                        tool_call_id=tool_call["id"]
                    ))

        final_answer = messages[-1].content if messages else "Could not compute answer."

        return {
            "retrieved_docs": docs,
            "context": context,
            "answer": final_answer,
            "messages": [AIMessage(content=final_answer)]
        }

    # ── Node 5: Compare node ─────────────────────────────────────────────────
    # Retrieves from all content types for comparison questions.

    def compare_node(state: MultimodalAgentState) -> dict:
        """Handles questions comparing text and visual content."""
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        # Retrieve from all content types
        retriever = vectorstore.as_retriever(search_kwargs={"k": 8})
        docs = retriever.invoke(last_human)
        context = format_docs_with_types(docs)

        response = llm.invoke([
            SystemMessage(content=COMPARE_SYSTEM_PROMPT),
            *state["messages"][:-1],
            HumanMessage(
                content=f"Combined context:\n{context}\n\nQuestion: {last_human}"
            )
        ])

        return {
            "retrieved_docs": docs,
            "context": context,
            "answer": response.content,
            "messages": [AIMessage(content=response.content)]
        }

    # ── Node 6: Web node ─────────────────────────────────────────────────────
    # Handles questions requiring web search.

    def web_node(state: MultimodalAgentState) -> dict:
        """Handles questions requiring current web information."""
        last_human = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                last_human = msg.content
                break

        web_result = web_search.invoke(last_human)

        response = llm.invoke([
            SystemMessage(content="You are a research assistant. "
                         "Answer based on the web search results below. "
                         "Cite sources from the search results."),
            HumanMessage(
                content=f"Web search results:\n{web_result}\n\nQuestion: {last_human}"
            )
        ])

        return {
            "retrieved_docs": [],
            "context": web_result,
            "answer": response.content,
            "messages": [AIMessage(content=response.content)]
        }

    # ── Routing function ──────────────────────────────────────────────────────

    def route_to_node(state: MultimodalAgentState) -> str:
        """
        Reads the route set by supervisor and returns the node name.
        This function is used by add_conditional_edges.
        """
        return state.get("route", "text")

    # ── Build graph ───────────────────────────────────────────────────────────

    graph = StateGraph(MultimodalAgentState)

    # Add all nodes
    graph.add_node("supervisor", supervisor_node)
    graph.add_node("text", text_node)
    graph.add_node("vision", vision_node)
    graph.add_node("tools", tools_node)
    graph.add_node("compare", compare_node)
    graph.add_node("web", web_node)

    # Entry point
    graph.set_entry_point("supervisor")

    # Supervisor routes to specialized nodes
    graph.add_conditional_edges(
        "supervisor",
        route_to_node,
        {
            "text": "text",
            "vision": "vision",
            "tools": "tools",
            "compare": "compare",
            "web": "web",
        }
    )

    # All specialized nodes go to END
    graph.add_edge("text", END)
    graph.add_edge("vision", END)
    graph.add_edge("tools", END)
    graph.add_edge("compare", END)
    graph.add_edge("web", END)

    return graph.compile()


def run_multimodal_agent(
    agent,
    question: str,
    chat_history: list = None
) -> str:
    """
    Runs the multimodal agent and returns the final answer.

    Args:
        agent:        compiled LangGraph agent
        question:     user's question
        chat_history: previous messages

    Returns:
        Final answer string
    """
    messages = list(chat_history or [])
    messages.append(HumanMessage(content=question))

    result = agent.invoke({
        "messages": messages,
        "route": "",
        "retrieved_docs": [],
        "context": "",
        "answer": ""
    })

    return result["answer"]